services:
  - type: web
    name: betting-website
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: npx nuxi preview --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000