services:
  - type: web
    name: betting-website
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    staticPublishDir: .output/public
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUXT_HOST
        value: 0.0.0.0
      - key: NUXT_PORT
        value: 3000